birthday1 = input("Enter sam's birthday in dd/mm/yyyy format")
birthday2 = input("Enter John's birthday in dd/mm/yyyy format")
birthday3 = input("Enter Alex's birthday in dd/mm/yyyy format")
print("Sam's birthday is on", birthday1)
print("John's birthday is on", birthday2)
print("Alex's birthday is on", birthday3)
